### ISSUE TITLE
National Spells & Rituals Not Generated

### ISSUE THREAD

**Issue by Moggers** [Logg-y/magicgen#10]
![image](https://user-images.githubusercontent.com/3508156/151683229-5cc1e622-bd9f-4877-9751-62131a748eae.png)

I'm assuming this is meant to be one of the national spells since its commented with "set param restricted to 120", but otherwise, I can see no national spells being generated.

Can you let me know what you want & need for debugging? I'll attach the nationgen and magicgen dm files to start with, you should be able to repro the issue with the nationgen dm.

[nationgen_dark_birch.txt](https://github.com/Logg-y/magicgen/files/7965125/nationgen_dark_birch.txt)
[magicgen-givememagic.txt](https://github.com/Logg-y/magicgen/files/7965126/magicgen-givememagic.txt)

**Pretty gnarly tool, by the way. Thank you very much for your work on this.**

**Comment by Logg-y** [comment]
Thanks, looks like this was a victim of my recent cleanup/refactoring efforts, will fix shortly.
