### ISSUE TITLE
getting this working in Ubuntu

### ISSUE THREAD

**Issue by darthlegit** [Logg-y/magicgen#5]
I am not an expert in Linux, but the code does not work out of the box in Ubuntu.

I had to change all the backslashes in path names to forward slashes in magicgen.py, and change the "python" to "python3" in line 56 of magicgenGUI.pyw. After that, it works fine!

Just thought this would be worth noting for when you expand compatibility. Thanks!

**Comment by Logg-y** [comment]
Thanks - I've implemented these things which should hopefully work in the next update.
