### ISSUE TITLE
fileparserutils missing from v3.1.0

### ISSUE THREAD

**Issue by Robbatog** [Logg-y/magicgen#9]
Trying to get magicgengui (or just magicgen, doesn't matter) to run for the first time. Get the error below. I know almost nothing about python, but in lib\fileparser there is no fileparserutils file, which I guess there should be?
Also, the path D:\Python38... confuses me since both my OS and magicgen is located in the C:\ drive.

![mgenerr](https://user-images.githubusercontent.com/22857548/143503452-d31d19f0-4620-4aca-943c-44891ce8c3f5.png)

**Comment by Logg-y** [comment]
Thanks, turns out that cx_freeze is more picky about these things that running on a local installation. You should hopefully find that 3.1.1 fixes this.
